-- 코드를 입력하세요
SELECT A.CART_ID
FROM (SELECT CART_ID 
      FROM CART_PRODUCTS 
      WHERE NAME IN ("Yogurt"))AS A
JOIN (SELECT CART_ID 
      FROM CART_PRODUCTS 
      WHERE NAME IN ("Milk")) AS B
ON A.CART_ID = B.CART_ID
ORDER BY CART_ID
