-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",A.BOARD_ID,"/",A.FILE_ID,A.FILE_NAME,A.FILE_EXT) AS C
FROM USED_GOODS_FILE AS A JOIN
(SELECT BOARD_ID ,MAX(VIEWS)
FROM USED_GOODS_BOARD
GROUP BY BOARD_ID
ORDER BY MAX(VIEWS) DESC
LIMIT 1) AS B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY C DESC