-- 코드를 입력하세요
SELECT A.WRITER_ID  ,B.NICKNAME ,
CONCAT(B.CITY,' ',B.STREET_ADDRESS1,' ',B.STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTR(TLNO,1,3),'-',SUBSTR(TLNO,4,4),'-',SUBSTR(TLNO,8,4))
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_USER AS B
ON A.WRITER_ID=B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(*)>2
ORDER BY A.WRITER_ID DESC