-- 코드를 입력하세요
SELECT C.REST_ID , C.REST_NAME, C.FOOD_TYPE,C.FAVORITES, C.ADDRESS , D.E AS SCORE
FROM REST_INFO AS C JOIN (SELECT A.REST_ID , ROUND(AVG(A.REVIEW_SCORE),2) AS E
FROM REST_REVIEW AS A JOIN REST_INFO AS B
ON A.REST_ID = B.REST_ID
WHERE B.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID) AS D
ON C.REST_ID = D.REST_ID
ORDER BY D.E DESC , C.FAVORITES DESC

